<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

/**
 * Generated by srag\PluginGenerator v0.13.8
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <info@studer-raimann.ch>
 */

require_once __DIR__ . "/vendor/srag/dic/src/PHPVersionChecker.php";

$id = "ocpc";
$version = "1.7.0";
$ilias_min_version = "6.0";
$ilias_max_version = "7.999";
$responsible = "fluxlabs ag";
$responsible_mail = "support@fluxlabs.ch";