<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../../vendor/autoload.php";

use srag\Plugins\OpencastPageComponent\Utils\OpencastPageComponentTrait;
use srag\RemovePluginDataConfirm\OpencastPageComponent\AbstractRemovePluginDataConfirm;

/**
 * Class OpencastPageComponentRemoveDataConfirm
 *
 * Generated by srag\PluginGenerator v0.13.8
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <info@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy OpencastPageComponentRemoveDataConfirm: ilUIPluginRouterGUI
 */
class OpencastPageComponentRemoveDataConfirm extends AbstractRemovePluginDataConfirm
{

    use OpencastPageComponentTrait;
    const PLUGIN_CLASS_NAME = ilOpencastPageComponentPlugin::class;
}
