<?php

/**
 * This file is part of ILIAS, a powerful learning management system
 * published by ILIAS open source e-Learning e.V.
 *
 * ILIAS is licensed with the GPL-3.0,
 * see https://www.gnu.org/licenses/gpl-3.0.en.html
 * You should have received a copy of said license along with the
 * source code, too.
 *
 * If this is not the case or you just want to try ILIAS, you'll find
 * us at:
 * https://www.ilias.de
 * https://github.com/ILIAS-eLearning
 *
 *********************************************************************/

use srag\Plugins\Opencast\UI\Integration\Integration;
use ILIAS\DI\Container;
use ILIAS\UI\Component\Input\Container\Form\Form;
use srag\Plugins\Opencast\Model\Event\EventAPIRepository;
use srag\Plugins\Opencast\Model\TermsOfUse\ToUManager;
use srag\Plugins\Opencast\DI\OpencastDIC;
use srag\Plugins\OpencastPageComponent\Config\Config;
use srag\Plugins\Opencast\Container\Init;
use ILIAS\Data\URI;
use srag\Plugins\OpencastPageComponent\Views\Edit;
use srag\Plugins\OpencastPageComponent\Translator;
use srag\Plugins\OpencastPageComponent\Views\InsertOrReplace;
use srag\Plugins\OpencastPageComponent\Views\Display;
use srag\Plugins\OpencastPageComponent\Views\EventDimensions;

/**
 * Class ilOpencastPageComponentPluginGUI
 *
 * Generated by srag\PluginGenerator v0.13.8
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <info@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy ilOpencastPageComponentPluginGUI: ilPCPluggedGUI
 */
class ilOpencastPageComponentPluginGUI extends ilPageComponentPluginGUI
{
    public const CMD_CANCEL = "cancel";
    public const CMD_CREATE = "create";
    public const CMD_CREATE_PLUG = "create_plug";
    public const CMD_EDIT = "edit";
    public const CMD_INSERT = "insert";
    public const CMD_UPDATE = "update";
    public const CMD_APPLY_FILTER = "applyFilter";
    public const CMD_RESET_FILTER = "resetFilter";
    public const CMD_SHOW_UPLOAD_FORM = 'showUploadForm';
    public const CMD_UPLOAD = 'upload';
    public const CUSTOM_CMD = 'ocpc_cmd';
    public const PROP_EVENT_ID = 'event_id';
    public const PROP_ASPECT_RATIO = 'ratio';
    public const PROP_WIDTH = 'width';
    public const PROP_HEIGHT = 'height';
    public const PROP_AS_LINK = 'as_link';
    public const POST_SIZE = 'size';
    public const MODE_EDIT = 'edit';
    public const MODE_PRESENTATION = 'presentation';
    public const MODE_PREVIEW = 'preview';
    public const PROP_POSITION = 'position';
    public const POSITION_LEFT = 'left';
    public const POSITION_CENTER = 'center';
    public const POSITION_RIGHT = 'right';
    public const PROP_RESPONSIVE = 'responsive';
    public const CMD_REPLACE = 'replace';
    public const P_PC_ID = 'pc_id';
    public const P_HIER_ID = 'hier_id';
    private \ilGlobalTemplateInterface $main_tpl;
    private \srag\Plugins\Opencast\Container\Container $container;
    private Translator $translator;
    private Integration $ui_integration;
    protected Container $dic;
    protected OpencastDIC $legacy_container;
    protected EventAPIRepository $event_repository;
    protected \ilOpenCastPlugin $opencast_plugin;

    /**
     * ilOpencastPageComponentPluginGUI constructor
     */
    public function __construct()
    {
        global $DIC;
        $this->dic = $DIC;
        $this->main_tpl = $this->dic->ui()->mainTemplate();
        $this->container = Init::init($DIC);
        $this->opencast_plugin = $this->container->plugin();
        $this->setPlugin(ilOpencastPageComponentPlugin::getInstance());
        $this->translator = new Translator($this->plugin, $this->container->translator());
        $this->ui_integration = $this->container->uiIntegration($this->plugin);

        $main_opencast_js_path = $this->opencast_plugin->getDirectory() . '/js/opencast/dist/index.js';
        if (file_exists($main_opencast_js_path)) {
            $this->dic->ui()->mainTemplate()->addJavaScript($main_opencast_js_path);
        }

        $this->legacy_container = $this->container->legacy();
        $this->legacy_container->overwriteService(
            'upload_handler',
            new xoctFileUploadHandlerGUI(
                $this->legacy_container->upload_storage_service(),
                $this->dic->ctrl()->getLinkTargetByClass(
                    [ilObjPluginDispatchGUI::class, ocpcRouterGUI::class, xoctFileUploadHandlerGUI::class],
                    'upload'
                ),
                $this->dic->ctrl()->getLinkTargetByClass(
                    [ilObjPluginDispatchGUI::class, ocpcRouterGUI::class, xoctFileUploadHandlerGUI::class],
                    'info'
                ),
                $this->dic->ctrl()->getLinkTargetByClass(
                    [ilObjPluginDispatchGUI::class, ocpcRouterGUI::class, xoctFileUploadHandlerGUI::class],
                    'remove'
                )
            )
        );

        $this->event_repository = $this->container[EventAPIRepository::class];

        parent::__construct();
    }

    /**
     * @deprecated We currently keep this snippet, although it is not used anymore. In older versions of the plugins
     * there was an implementation like this, If we face an issue with the parameters in the future, we can
     *             restore this method.
     */
    private function ensureParameters(bool $all = false): void
    {
        $query_params = $this->dic->http()->request()->getQueryParams();
        if (!$all) {
            $content_object = isset($this->pc_gui) ? $this->getPCGUI()->getContentObject() : null;
            $this->dic->ctrl()->setParameter(
                $this,
                self::P_PC_ID,
                $query_params[self::P_PC_ID] ?? $content_object?->readPCId() ?? ''
            );
            $this->dic->ctrl()->setParameter(
                $this,
                self::P_HIER_ID,
                $query_params[self::P_HIER_ID] ?? '1'
            );
        }

        $this->dic->ctrl()->setParameter(
            $this,
            'rtoken',
            $query_params['rtoken'] ?? null
        );
    }

    public function executeCommand(): void
    {
        try {
            $this->dic->ctrl()->getNextClass();
            $cmd = $this->dic->ctrl()->getCmd();
            $custom_command = $this->dic->http()->request()->getQueryParams()[self::CUSTOM_CMD] ?? null;

            if ($cmd === self::CMD_INSERT && $custom_command !== null) {
                $cmd = $custom_command;
                $this->performCommand($cmd);
                return;
            }

            $this->performCommand(
                $this->dic->ctrl()->getCmd()
            );
            return;
        } catch (ilException $e) {
            $this->main_tpl->setOnScreenMessage('failure', $e->getMessage(), true);
            $this->dic->ctrl()->returnToParent($this);
        }
    }

    public function performCommand(string $cmd): void
    {
        switch ($cmd) {
            case self::CMD_CANCEL:
            case self::CMD_CREATE:
            case self::CMD_INSERT:
            case self::CMD_EDIT:
            case self::CMD_UPDATE:
            case self::CMD_APPLY_FILTER:
            case self::CMD_RESET_FILTER:
            case self::CMD_SHOW_UPLOAD_FORM:
            case self::CMD_UPLOAD:
            case self::CMD_REPLACE:
                $this->{$cmd}();
                break;
            default:
                break;
        }
    }

    // performing commands
    public function cancel(): void
    {
        $this->returnToParent();
    }

    /**
     * @deprecated still in use?
     */
    protected function upload(): void
    {
        trigger_error(
            'Method ' . __METHOD__ . ' is deprecated and should not be used anymore.',
            E_USER_DEPRECATED
        );
    }

    private function buildURI(string $command): URI
    {
        return new URI(rtrim(ILIAS_HTTP_PATH, '/') . '/' . $this->dic->ctrl()->getLinkTarget($this, $command));
    }

    public function replace(): void
    {
        $insert = new InsertOrReplace(
            $this->container,
            $this->translator,
            $this->ui_integration,
            $this->buildURI(self::CMD_REPLACE),
            $this->buildURI(self::CMD_UPDATE)
        );
        $this->main_tpl->setContent(
            $this->dic->ui()->renderer()->render(
                $insert->get()
            )
        );
    }

    public function insert(): void
    {
        $insert = new InsertOrReplace(
            $this->container,
            $this->translator,
            $this->ui_integration,
            $this->buildURI(self::CMD_INSERT),
            $this->buildURI(self::CMD_CREATE)
        );
        $this->main_tpl->setContent(
            $this->dic->ui()->renderer()->render(
                $insert->get()
            )
        );
        // must be after to avoid changed URLs
        $this->addToolbar();
    }

    public function create(): void
    {
        $query_params = $this->dic->http()->request()->getQueryParams();
        $event_id = $query_params[self::PROP_EVENT_ID] ?? null;

        // determine width/height of event
        $event_ratio = (new EventDimensions($this->event_repository))->determineForEventId($event_id);

        $properties = [
            self::PROP_EVENT_ID => $event_id,
            self::PROP_HEIGHT => $event_ratio?->getHeight() ?? max(
                (int) Config::getField(Config::KEY_DEFAULT_HEIGHT),
                Config::DEFAULT_HEIGHT
            ),
            self::PROP_WIDTH => $event_ratio?->getWidth() ?? max(
                (int) Config::getField(Config::KEY_DEFAULT_WIDTH),
                Config::DEFAULT_WIDTH
            ),
            self::PROP_POSITION => self::POSITION_LEFT,
            self::PROP_RESPONSIVE => true,
            self::PROP_AS_LINK => (bool) Config::getField(Config::KEY_DEFAULT_AS_LINK),
            self::PROP_ASPECT_RATIO => Edit::RATIO_AS_PUBLICATION,
        ];
        $this->createElement($properties);
        $this->main_tpl->setOnScreenMessage('success', $this->translator->translate('msg_added'), true);

        $this->dic->ctrl()->redirect($this, self::CMD_EDIT);
    }

    private function getEditView(): Edit
    {
        return new Edit(
            $this->getProperties(),
            $this->container,
            $this->translator,
            $this->ui_integration,
            $this->buildURI(self::CMD_UPDATE),
            $this->buildURI(self::CMD_REPLACE),
        );
    }

    public function edit(): void
    {
        $this->main_tpl->setContent(
            $this->dic->ui()->renderer()->render($this->getEditView()->get())
        );
    }

    public function update(): void
    {
        $current_properties = $this->getProperties();
        // retrieve new event id if changed
        $event_id = $this->dic->http()->request()->getQueryParams()[self::PROP_EVENT_ID] ?? null;
        if ($event_id !== null) {
            $this->main_tpl->setOnScreenMessage('success', $this->translator->translate('msg_replaced'), true);
            $current_properties[self::PROP_EVENT_ID] = $event_id;
            $this->updateElement($current_properties);
        }

        $edit = $this->getEditView();
        $updated_properties = $edit->getUpdatedProperties($this->dic->http()->request());

        if ($updated_properties === null || $event_id !== null) {
            $this->main_tpl->setContent(
                $this->dic->ui()->renderer()->render($edit->get())
            );
            return;
        }

        $properties = array_merge($current_properties, $updated_properties);
        $this->updateElement($properties);
        $this->returnToParent();
    }

    // END performing commands

    protected function addToolbar(): void
    {
        $upload_button = ilLinkButton::getInstance();
        $upload_button->setPrimary(true);
        $this->dic->ctrl()->setParameter($this, self::CUSTOM_CMD, self::CMD_SHOW_UPLOAD_FORM);
        $upload_button->setUrl($this->dic->ctrl()->getLinkTarget($this, self::CMD_INSERT));
        $upload_button->setCaption($this->translator->translate('btn_upload'), false);
        $this->dic->toolbar()->addButtonInstance($upload_button);
    }

    protected function showUploadForm(): void
    {
        $form = $this->getUploadForm();
        $this->main_tpl->setContent(
            $this->dic->ui()->renderer()->render($form)
        );
    }

    protected function getUploadForm(): Form
    {
        $return_link = $this->dic->ctrl()->getLinkTarget($this, 'insert_plug_OpencastPageComponent');
        $this->dic->ctrl()->setParameterByClass(
            ocpcRouterGUI::class,
            ocpcRouterGUI::P_GET_RETURN_LINK,
            urlencode($return_link)
        );

        $with_terms_of_use = !ToUManager::hasAcceptedToU($this->dic->user()->getId());

        $form_action_by_class = $this->dic->ctrl()->getFormActionByClass(
            [ilObjPluginDispatchGUI::class, ocpcRouterGUI::class],
            self::CMD_CREATE
        );

        return $this->legacy_container->event_form_builder()->upload(
            $form_action_by_class,
            $with_terms_of_use
        );
    }

    public function getElementHTML($a_mode, array $a_properties, $plugin_version): string
    {
        $display = new Display(
            $a_properties,
            $this->container,
            $a_mode
        );

        return $this->dic->ui()->renderer()->render(
            $display->get()
        );
    }

    private function redirect(string $cmd): void
    {
        $this->dic->ctrl()->setParameter($this, self::CUSTOM_CMD, $cmd);
        $this->dic->ctrl()->redirect($this, self::CMD_INSERT);
    }

}
