<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\OpencastPageComponent\Config;

use srag\Plugins\OpencastPageComponent\Utils\OpencastPageComponentTrait;
use ilOpencastPageComponentPlugin;
use ilTextInputGUI;
use srag\ActiveRecordConfig\OpencastPageComponent\ActiveRecordConfigFormGUI;

/**
 * Class ConfigFormGUI
 *
 * Generated by srag\PluginGenerator v0.13.8
 *
 * @package srag\Plugins\OpencastPageComponent\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <info@studer-raimann.ch>
 */
class ConfigFormGUI extends ActiveRecordConfigFormGUI
{

    use OpencastPageComponentTrait;
    const PLUGIN_CLASS_NAME = ilOpencastPageComponentPlugin::class;
    const CONFIG_CLASS_NAME = Config::class;


    /**
     * @inheritdoc
     */
    protected function initFields()/*: void*/
    {
        $this->fields = [
            Config::KEY_SOME => [
                self::PROPERTY_CLASS    => ilTextInputGUI::class,
                self::PROPERTY_REQUIRED => true
            ]
        ];
        // TODO: Implement ConfigFormGUI
    }
}
