<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\OpencastPageComponent\Utils;

/**
 * Trait OpencastPageComponentTrait
 *
 * Generated by srag\PluginGenerator v0.13.8
 *
 * @package srag\Plugins\OpencastPageComponent\Utils
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <info@studer-raimann.ch>
 */
trait OpencastPageComponentTrait
{

}
